# Generated by Django 4.2.7 on 2023-11-09 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0003_alter_realestetimgaes_real_estet_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='realestate',
            name='floor',
        ),
        migrations.AlterField(
            model_name='realestate',
            name='status_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.status'),
        ),
    ]
