# Generated by Django 4.2.7 on 2023-11-09 11:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0004_remove_realestate_floor_alter_realestate_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BuyRealEstet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('real_estet_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
