# Generated by Django 4.2.7 on 2023-11-09 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0002_pyemntsumm_customuser_summ'),
        ('real_estate', '0005_realestate_is_active_buyrealestet'),
    ]

    operations = [
        migrations.AddField(
            model_name='realestate',
            name='is_payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='realestate',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='authentications.pyemntsumm'),
        ),
    ]
