# Generated by Django 4.2.7 on 2023-11-10 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0010_alter_realestate_price_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='number_romm_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.numberrooms'),
        ),
    ]
