# Generated by Django 4.2.7 on 2023-11-10 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0011_alter_realestate_number_romm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
