# Generated by Django 4.2.7 on 2023-11-10 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0012_alter_realestate_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realestate',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
