# Generated by Django 4.2.7 on 2023-11-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('real_estate', '0013_alter_realestate_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyrealestet',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
