# Generated by Django 4.2.7 on 2023-11-10 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('real_estate', '0014_buyrealestet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyrealestet',
            name='real_estet_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='real_estate.realestate'),
        ),
        migrations.AlterField(
            model_name='buyrealestet',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
