# Generated by Django 4.2.7 on 2023-11-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0003_alter_pyemntsumm_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pyemntsumm',
            name='summ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
