# Generated by Django 4.2.7 on 2023-11-10 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentications', '0004_alter_pyemntsumm_summ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='summ',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
